# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# 版本对应关系查这里：https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=0.1.0
group=com.mchanhua

# Dependencies
fabric_api_version=0.155.3+26.1.2
